f=open('C:\\Users\\user\\ege_inf\\EGE-inf\\24\\24\\24var09-12.txt')
file_list = f.readline()
f.close()
file_list = file_list.replace('00', '0 0')
file_list = file_list.split(' ')
print( max(map(len, file_list)))  
